# Generated by Django 5.0.7 on 2024-08-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='published'),
        ),
    ]
