# Generated by Django 5.0.7 on 2024-08-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='publish'),
        ),
    ]
