from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from user.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    is_provider = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ('email', 'password')


class ResetPasswordForm(forms.Form):
    #   TODO: Background service for resetting passwords via autogenerated link sent on email
    email = forms.EmailField()
